# # PDE parameter 
nx = 100
ny = 100

D_u = 0.5
D_x = 0.05
Lx = 100.0
Ly = 100.0
N = 2000
cutoff = 15.0
d = 0.3
l = 1.5
lambda = 150.0
mu = 50.0
periodic = true
t_end = 500.0
t_save = 0.0
t_start = 0.0
t_step = 5.0

init = "Antoine_1"
freq = 2