l = 1.5
d = 0.3
cutoff = 20.0    
N = 2000
t_step = 1.0
t_save = 0.0
t_start = 0.0
t_end = 100.0
Lx = 50.0
Ly = 50.0
mu = 100.0
lambda = 1.0
D_x  = 0.01
D_u =  0.001
periodic = true

# PDE parameter 
nx = 100
ny = 100