nx = 100
ny = 100

D_u = 0.0
D_x = 0.0001
Lx = 100.0
Ly = 100.0

N = 10000

cutoff_factor = 4 

density = 1.0
chi = 0.9

lambda = 150.0
mu = 10.0
periodic = true

t_end = 10000.0
t_save = 0.0
t_start = 0.0
t_step = 5.0

init = "random"
init_spread = 40
freq = 2